# Generated by Django 4.2.8 on 2024-01-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Userprofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=15)),
                ("phone_number", models.CharField(max_length=200)),
            ],
        ),
    ]
