# Generated by Django 4.2.8 on 2024-01-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshopapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.IntegerField(unique=True)),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=250)),
                ("author", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=100)),
                ("image_path", models.CharField(max_length=255)),
            ],
        ),
    ]
