# Generated by Django 4.2.8 on 2024-01-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookshopapp", "0005_purchaseditem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseditem",
            name="cart_item",
        ),
        migrations.AddField(
            model_name="purchaseditem",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookshopapp.book",
            ),
        ),
    ]
